### ISSUE TITLE
CPU frequency UI update bug

### ISSUE THREAD

**Issue by Chris54721** [Evisceration/DeviceControl#15]
[This line](https://github.com/Evisceration/DeviceControl/blob/master/app/src/main/java/org/namelessrom/devicecontrol/modules/cpu/CpuSettingsFragment.java#L424) throws a `java.lang.NumberFormatException: Invalid int: "XXXX MHz"`. Sometimes this causes the min/max frequencies to change when they shouldn't.

The reason for that should be pretty obvious; can't make a PR right now, but I can do so later if needed.

EDIT: of course this happens with [this line](https://github.com/Evisceration/DeviceControl/blob/master/app/src/main/java/org/namelessrom/devicecontrol/modules/cpu/CpuSettingsFragment.java#L434) as well

**Comment by Evisceration** [comment]
thanks again :)

it seems that my custom preference library does not work like the real listpreference does and i needed to do extra changes than just dropping the library in.

https://github.com/Evisceration/DeviceControl/commit/0e1fc3c5d70e511a14fb575aadf117cba34cb1ef
should fix it

**Comment by Chris54721** [comment]
Great :+1:
