### ISSUE TITLE
superuser binary messege comes twice

### ISSUE THREAD

**Issue by h2yk** [Evisceration/DeviceControl#24]
In night theme mode,the superuser binary warning messege (you installed superuser…)comes twice.
tested on my device huaweiP10lite and huaweiP8lite
here are the screenshots:
![screenshot_20170918-182851](https://user-images.githubusercontent.com/32059738/30536039-4ff60350-9c9f-11e7-809a-340c1012f27b.png)
![screenshot_20170918-182854](https://user-images.githubusercontent.com/32059738/30536024-44474c62-9c9f-11e7-976b-8bedd357d98c.png)

sorry for my bad English…

**Comment by amartinz** [comment]
also happens if it asks for new permissions, thanks for reporting!

**Comment by amartinz** [comment]
pushed a new beta, please let me know if this issue is fixed for you!

**Comment by h2yk** [comment]
…the messege never comes
(still using magiskSU…)
![screenshot_20170919-083957](https://user-images.githubusercontent.com/32059738/30569501-3c44c3d8-9d16-11e7-90a4-e5645f3a8d39.png)

**Comment by amartinz** [comment]
yes, because i removed the magisk check, because i tested it with magisk and it works fine :)

**Comment by h2yk** [comment]
oh,thanks!
and I have one more important issue(meybe),so i'll open it soon…
